sonata_block:
    default_contexts: [admin]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

#sonata_intl:
#    timezone:
#        default: Europe/Paris

sonata_admin:
    title:          'SMART BOOSTER'
    options:
        title_mode: 'single_text'

    security:
        handler: sonata.admin.security.handler.noop

    templates:
        layout: admin/layout.html.twig
        user_block: "@SmartSonata/block/user.html.twig"

    dashboard:
        groups:
            users:
                label: dashboard.label_users
                label_catalogue: admin
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user.administrator
