_admin:
    resource: routing/admin.yml
    host:     "admin.%domain%"

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true