admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
        
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

security:
    resource: admin/security.yml

admin_dashboard:
    path:    /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true
